In [2]:
import pandas as pd

df = pd.read_csv("AAPL_NO_DATES.csv")
df.head()

         Open        High         Low       Close   Adj Close     Volume
0  196.240005  196.729996  195.279999  195.610001  194.576660   35175100
1  195.039993  195.179993  191.850006  192.580002  191.562653   50389300
2  191.570007  192.369995  190.690002  191.169998  190.160110   61235200
3  185.520004  187.380005  181.919998  181.990005  181.028610  115799700
4  182.130005  183.130005  177.350006  178.850006  177.905197   97576100

In [22]:
pd.date_range(start='3/1/2020', end = '4/2/2020', freq = 'B')

DatetimeIndex(['2020-03-02', '2020-03-03', '2020-03-04', '2020-03-05',
               '2020-03-06', '2020-03-09', '2020-03-10', '2020-03-11',
               '2020-03-12', '2020-03-13', '2020-03-16', '2020-03-17',
               '2020-03-18', '2020-03-19', '2020-03-20', '2020-03-23',
               '2020-03-24', '2020-03-25', '2020-03-26', '2020-03-27',
               '2020-03-30', '2020-03-31', '2020-04-01', '2020-04-02'],
              dtype='datetime64[ns]', freq='B')

In [12]:
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

usb = CustomBusinessDay(calendar=USFederalHolidayCalendar())
usb

In [26]:
rng = pd.date_range(start='3/1/2020', end = '4/1/2020', freq = usb)

In [27]:
df.set_index(rng, inplace= True)
df

,Open,High,Low,Close,Adj Close,Volume
2020-03-02,196.240005,196.729996,195.279999,195.610001,194.576660,35175100
2020-03-03,195.039993,195.179993,191.850006,192.580002,191.562653,50389300
2020-03-04,191.570007,192.369995,190.690002,191.169998,190.160110,61235200
2020-03-05,185.520004,187.380005,181.919998,181.990005,181.028610,115799700
2020-03-06,182.130005,183.130005,177.350006,178.850006,177.905197,97576100
2020-03-09,179.690002,180.270004,177.580002,179.800003,178.850159,67823000
2020-03-10,180.869995,180.929993,177.009995,178.190002,177.248672,60378500
2020-03-11,179.479996,180.750000,177.600006,177.970001,177.029861,54686900
2020-03-12,177.320007,178.619995,176.550003,177.789993,177.089615,51988100
2020-03-13,177.970001,179.690002,177.309998,179.460007,178.753036,43675600
2020-03-16,178.880005,179.479996,177.050003,177.449997,176.750946,43622600
2020-03-17,177.130005,178.539993,176.500000,176.570007,175.874420,46964900
2020-03-18,177.139999,177.509995,173.479996,174.000000,173.314529,66062900
2020-03-19,172.300003,175.100006,171.960007,174.490005,173.802628,61114200
2020-03-20,175.070007,176.130005,173.740005,175.839996,175.147278,46311900
2020-03-23,177.059998,177.679993,176.250000,177.229996,176.531799,42084200
2020-03-24,178.520004,181.550003,178.330002,181.119995,180.406479,52722800
2020-03-25,180.669998,181.100006,176.009995,176.380005,175.685165,54945800
2020-03-26,177.380005,179.149994,175.820007,178.610001,177.906372,51449600
2020-03-27,180.089996,180.589996,178.550003,180.190002,179.480164,43820700
2020-03-30,179.699997,184.899994,179.500000,184.119995,183.394653,53003900
2020-03-31,184.940002,187.850006,184.740005,187.649994,186.910751,60813900
2020-04-01,187.839996,189.119995,187.479996,187.869995,187.129898,60794500